/*
DRACOON API

REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>

API version: 5.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LastAdminUserRoomList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LastAdminUserRoomList{}

// LastAdminUserRoomList List of (last admin user) rooms
type LastAdminUserRoomList struct {
	// List of last admin rooms
	Items []LastAdminUserRoom `json:"items"`
}

type _LastAdminUserRoomList LastAdminUserRoomList

// NewLastAdminUserRoomList instantiates a new LastAdminUserRoomList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLastAdminUserRoomList(items []LastAdminUserRoom) *LastAdminUserRoomList {
	this := LastAdminUserRoomList{}
	this.Items = items
	return &this
}

// NewLastAdminUserRoomListWithDefaults instantiates a new LastAdminUserRoomList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLastAdminUserRoomListWithDefaults() *LastAdminUserRoomList {
	this := LastAdminUserRoomList{}
	return &this
}

// GetItems returns the Items field value
func (o *LastAdminUserRoomList) GetItems() []LastAdminUserRoom {
	if o == nil {
		var ret []LastAdminUserRoom
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *LastAdminUserRoomList) GetItemsOk() ([]LastAdminUserRoom, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *LastAdminUserRoomList) SetItems(v []LastAdminUserRoom) {
	o.Items = v
}

func (o LastAdminUserRoomList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LastAdminUserRoomList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *LastAdminUserRoomList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLastAdminUserRoomList := _LastAdminUserRoomList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLastAdminUserRoomList)

	if err != nil {
		return err
	}

	*o = LastAdminUserRoomList(varLastAdminUserRoomList)

	return err
}

type NullableLastAdminUserRoomList struct {
	value *LastAdminUserRoomList
	isSet bool
}

func (v NullableLastAdminUserRoomList) Get() *LastAdminUserRoomList {
	return v.value
}

func (v *NullableLastAdminUserRoomList) Set(val *LastAdminUserRoomList) {
	v.value = val
	v.isSet = true
}

func (v NullableLastAdminUserRoomList) IsSet() bool {
	return v.isSet
}

func (v *NullableLastAdminUserRoomList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLastAdminUserRoomList(val *LastAdminUserRoomList) *NullableLastAdminUserRoomList {
	return &NullableLastAdminUserRoomList{value: val, isSet: true}
}

func (v NullableLastAdminUserRoomList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLastAdminUserRoomList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
