/*
DRACOON API

REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>

API version: 5.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserFileKeyList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserFileKeyList{}

// UserFileKeyList Mandatory for encrypted shares
type UserFileKeyList struct {
	// List of user file keys
	Items []UserFileKey `json:"items,omitempty"`
}

// NewUserFileKeyList instantiates a new UserFileKeyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserFileKeyList() *UserFileKeyList {
	this := UserFileKeyList{}
	return &this
}

// NewUserFileKeyListWithDefaults instantiates a new UserFileKeyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserFileKeyListWithDefaults() *UserFileKeyList {
	this := UserFileKeyList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *UserFileKeyList) GetItems() []UserFileKey {
	if o == nil || IsNil(o.Items) {
		var ret []UserFileKey
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserFileKeyList) GetItemsOk() ([]UserFileKey, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *UserFileKeyList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []UserFileKey and assigns it to the Items field.
func (o *UserFileKeyList) SetItems(v []UserFileKey) {
	o.Items = v
}

func (o UserFileKeyList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserFileKeyList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableUserFileKeyList struct {
	value *UserFileKeyList
	isSet bool
}

func (v NullableUserFileKeyList) Get() *UserFileKeyList {
	return v.value
}

func (v *NullableUserFileKeyList) Set(val *UserFileKeyList) {
	v.value = val
	v.isSet = true
}

func (v NullableUserFileKeyList) IsSet() bool {
	return v.isSet
}

func (v *NullableUserFileKeyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserFileKeyList(val *UserFileKeyList) *NullableUserFileKeyList {
	return &NullableUserFileKeyList{value: val, isSet: true}
}

func (v NullableUserFileKeyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserFileKeyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
