/*
DRACOON API

REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>

API version: 5.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CreateFolderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFolderRequest{}

// CreateFolderRequest Request model for creating a folder
type CreateFolderRequest struct {
	// Parent node ID (room or folder)
	ParentId int64 `json:"parentId"`
	// Name
	Name string `json:"name"`
	// User notes  Use empty string to remove.
	Notes *string `json:"notes,omitempty"`
	// &#128640; Since v4.30.0  Classification ID:  * `1` - public  * `2` - internal  * `3` - confidential  * `4` - strictly confidential    Provided (or default) classification is taken from room  when file gets uploaded without any classification.
	Classification *int32 `json:"classification,omitempty"`
	// &#128640; Since v4.22.0  Time the node was created on external file system  (default: current server datetime in UTC format)
	TimestampCreation *time.Time `json:"timestampCreation,omitempty"`
	// &#128640; Since v4.22.0  Time the content of a node was last modified on external file system  (default: current server datetime in UTC format)
	TimestampModification *time.Time `json:"timestampModification,omitempty"`
}

type _CreateFolderRequest CreateFolderRequest

// NewCreateFolderRequest instantiates a new CreateFolderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFolderRequest(parentId int64, name string) *CreateFolderRequest {
	this := CreateFolderRequest{}
	this.ParentId = parentId
	this.Name = name
	return &this
}

// NewCreateFolderRequestWithDefaults instantiates a new CreateFolderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFolderRequestWithDefaults() *CreateFolderRequest {
	this := CreateFolderRequest{}
	return &this
}

// GetParentId returns the ParentId field value
func (o *CreateFolderRequest) GetParentId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value
// and a boolean to check if the value has been set.
func (o *CreateFolderRequest) GetParentIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentId, true
}

// SetParentId sets field value
func (o *CreateFolderRequest) SetParentId(v int64) {
	o.ParentId = v
}

// GetName returns the Name field value
func (o *CreateFolderRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateFolderRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateFolderRequest) SetName(v string) {
	o.Name = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *CreateFolderRequest) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFolderRequest) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *CreateFolderRequest) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *CreateFolderRequest) SetNotes(v string) {
	o.Notes = &v
}

// GetClassification returns the Classification field value if set, zero value otherwise.
func (o *CreateFolderRequest) GetClassification() int32 {
	if o == nil || IsNil(o.Classification) {
		var ret int32
		return ret
	}
	return *o.Classification
}

// GetClassificationOk returns a tuple with the Classification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFolderRequest) GetClassificationOk() (*int32, bool) {
	if o == nil || IsNil(o.Classification) {
		return nil, false
	}
	return o.Classification, true
}

// HasClassification returns a boolean if a field has been set.
func (o *CreateFolderRequest) HasClassification() bool {
	if o != nil && !IsNil(o.Classification) {
		return true
	}

	return false
}

// SetClassification gets a reference to the given int32 and assigns it to the Classification field.
func (o *CreateFolderRequest) SetClassification(v int32) {
	o.Classification = &v
}

// GetTimestampCreation returns the TimestampCreation field value if set, zero value otherwise.
func (o *CreateFolderRequest) GetTimestampCreation() time.Time {
	if o == nil || IsNil(o.TimestampCreation) {
		var ret time.Time
		return ret
	}
	return *o.TimestampCreation
}

// GetTimestampCreationOk returns a tuple with the TimestampCreation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFolderRequest) GetTimestampCreationOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimestampCreation) {
		return nil, false
	}
	return o.TimestampCreation, true
}

// HasTimestampCreation returns a boolean if a field has been set.
func (o *CreateFolderRequest) HasTimestampCreation() bool {
	if o != nil && !IsNil(o.TimestampCreation) {
		return true
	}

	return false
}

// SetTimestampCreation gets a reference to the given time.Time and assigns it to the TimestampCreation field.
func (o *CreateFolderRequest) SetTimestampCreation(v time.Time) {
	o.TimestampCreation = &v
}

// GetTimestampModification returns the TimestampModification field value if set, zero value otherwise.
func (o *CreateFolderRequest) GetTimestampModification() time.Time {
	if o == nil || IsNil(o.TimestampModification) {
		var ret time.Time
		return ret
	}
	return *o.TimestampModification
}

// GetTimestampModificationOk returns a tuple with the TimestampModification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFolderRequest) GetTimestampModificationOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimestampModification) {
		return nil, false
	}
	return o.TimestampModification, true
}

// HasTimestampModification returns a boolean if a field has been set.
func (o *CreateFolderRequest) HasTimestampModification() bool {
	if o != nil && !IsNil(o.TimestampModification) {
		return true
	}

	return false
}

// SetTimestampModification gets a reference to the given time.Time and assigns it to the TimestampModification field.
func (o *CreateFolderRequest) SetTimestampModification(v time.Time) {
	o.TimestampModification = &v
}

func (o CreateFolderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFolderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parentId"] = o.ParentId
	toSerialize["name"] = o.Name
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Classification) {
		toSerialize["classification"] = o.Classification
	}
	if !IsNil(o.TimestampCreation) {
		toSerialize["timestampCreation"] = o.TimestampCreation
	}
	if !IsNil(o.TimestampModification) {
		toSerialize["timestampModification"] = o.TimestampModification
	}
	return toSerialize, nil
}

func (o *CreateFolderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"parentId",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateFolderRequest := _CreateFolderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateFolderRequest)

	if err != nil {
		return err
	}

	*o = CreateFolderRequest(varCreateFolderRequest)

	return err
}

type NullableCreateFolderRequest struct {
	value *CreateFolderRequest
	isSet bool
}

func (v NullableCreateFolderRequest) Get() *CreateFolderRequest {
	return v.value
}

func (v *NullableCreateFolderRequest) Set(val *CreateFolderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFolderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFolderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFolderRequest(val *CreateFolderRequest) *NullableCreateFolderRequest {
	return &NullableCreateFolderRequest{value: val, isSet: true}
}

func (v NullableCreateFolderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFolderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
