/*
DRACOON API

REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>

API version: 5.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ThirdPartyDependenciesData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThirdPartyDependenciesData{}

// ThirdPartyDependenciesData Third-party dependency information
type ThirdPartyDependenciesData struct {
	// Third party dependencies id
	Id string `json:"id"`
	// Third party dependencies name
	Name string `json:"name"`
	// Third party dependencies url
	Url string `json:"url"`
	// Third party dependencies description
	Description string `json:"description"`
	// Third party dependencies groupId
	GroupId string `json:"groupId"`
	// Third party dependencies artifactId
	ArtifactId string `json:"artifactId"`
	// Third party dependencies version
	Version string `json:"version"`
	// Third party dependencies type
	Type string `json:"type"`
	// Third party dependencies licenses type
	Licenses []string `json:"licenses"`
}

type _ThirdPartyDependenciesData ThirdPartyDependenciesData

// NewThirdPartyDependenciesData instantiates a new ThirdPartyDependenciesData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThirdPartyDependenciesData(id string, name string, url string, description string, groupId string, artifactId string, version string, type_ string, licenses []string) *ThirdPartyDependenciesData {
	this := ThirdPartyDependenciesData{}
	this.Id = id
	this.Name = name
	this.Url = url
	this.Description = description
	this.GroupId = groupId
	this.ArtifactId = artifactId
	this.Version = version
	this.Type = type_
	this.Licenses = licenses
	return &this
}

// NewThirdPartyDependenciesDataWithDefaults instantiates a new ThirdPartyDependenciesData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThirdPartyDependenciesDataWithDefaults() *ThirdPartyDependenciesData {
	this := ThirdPartyDependenciesData{}
	return &this
}

// GetId returns the Id field value
func (o *ThirdPartyDependenciesData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ThirdPartyDependenciesData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ThirdPartyDependenciesData) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ThirdPartyDependenciesData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ThirdPartyDependenciesData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ThirdPartyDependenciesData) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *ThirdPartyDependenciesData) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ThirdPartyDependenciesData) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ThirdPartyDependenciesData) SetUrl(v string) {
	o.Url = v
}

// GetDescription returns the Description field value
func (o *ThirdPartyDependenciesData) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ThirdPartyDependenciesData) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ThirdPartyDependenciesData) SetDescription(v string) {
	o.Description = v
}

// GetGroupId returns the GroupId field value
func (o *ThirdPartyDependenciesData) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *ThirdPartyDependenciesData) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *ThirdPartyDependenciesData) SetGroupId(v string) {
	o.GroupId = v
}

// GetArtifactId returns the ArtifactId field value
func (o *ThirdPartyDependenciesData) GetArtifactId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArtifactId
}

// GetArtifactIdOk returns a tuple with the ArtifactId field value
// and a boolean to check if the value has been set.
func (o *ThirdPartyDependenciesData) GetArtifactIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArtifactId, true
}

// SetArtifactId sets field value
func (o *ThirdPartyDependenciesData) SetArtifactId(v string) {
	o.ArtifactId = v
}

// GetVersion returns the Version field value
func (o *ThirdPartyDependenciesData) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ThirdPartyDependenciesData) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ThirdPartyDependenciesData) SetVersion(v string) {
	o.Version = v
}

// GetType returns the Type field value
func (o *ThirdPartyDependenciesData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ThirdPartyDependenciesData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ThirdPartyDependenciesData) SetType(v string) {
	o.Type = v
}

// GetLicenses returns the Licenses field value
func (o *ThirdPartyDependenciesData) GetLicenses() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value
// and a boolean to check if the value has been set.
func (o *ThirdPartyDependenciesData) GetLicensesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Licenses, true
}

// SetLicenses sets field value
func (o *ThirdPartyDependenciesData) SetLicenses(v []string) {
	o.Licenses = v
}

func (o ThirdPartyDependenciesData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThirdPartyDependenciesData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	toSerialize["description"] = o.Description
	toSerialize["groupId"] = o.GroupId
	toSerialize["artifactId"] = o.ArtifactId
	toSerialize["version"] = o.Version
	toSerialize["type"] = o.Type
	toSerialize["licenses"] = o.Licenses
	return toSerialize, nil
}

func (o *ThirdPartyDependenciesData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"url",
		"description",
		"groupId",
		"artifactId",
		"version",
		"type",
		"licenses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varThirdPartyDependenciesData := _ThirdPartyDependenciesData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varThirdPartyDependenciesData)

	if err != nil {
		return err
	}

	*o = ThirdPartyDependenciesData(varThirdPartyDependenciesData)

	return err
}

type NullableThirdPartyDependenciesData struct {
	value *ThirdPartyDependenciesData
	isSet bool
}

func (v NullableThirdPartyDependenciesData) Get() *ThirdPartyDependenciesData {
	return v.value
}

func (v *NullableThirdPartyDependenciesData) Set(val *ThirdPartyDependenciesData) {
	v.value = val
	v.isSet = true
}

func (v NullableThirdPartyDependenciesData) IsSet() bool {
	return v.isSet
}

func (v *NullableThirdPartyDependenciesData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThirdPartyDependenciesData(val *ThirdPartyDependenciesData) *NullableThirdPartyDependenciesData {
	return &NullableThirdPartyDependenciesData{value: val, isSet: true}
}

func (v NullableThirdPartyDependenciesData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThirdPartyDependenciesData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
