/*
DRACOON API

REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>

API version: 5.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MfaPoliciesConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MfaPoliciesConfig{}

// MfaPoliciesConfig Set of multi-factor authentication policies
type MfaPoliciesConfig struct {
	// Determines whether multi-factor authentication is enforced
	IsMfaEnforced bool `json:"isMfaEnforced"`
}

type _MfaPoliciesConfig MfaPoliciesConfig

// NewMfaPoliciesConfig instantiates a new MfaPoliciesConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMfaPoliciesConfig(isMfaEnforced bool) *MfaPoliciesConfig {
	this := MfaPoliciesConfig{}
	this.IsMfaEnforced = isMfaEnforced
	return &this
}

// NewMfaPoliciesConfigWithDefaults instantiates a new MfaPoliciesConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMfaPoliciesConfigWithDefaults() *MfaPoliciesConfig {
	this := MfaPoliciesConfig{}
	return &this
}

// GetIsMfaEnforced returns the IsMfaEnforced field value
func (o *MfaPoliciesConfig) GetIsMfaEnforced() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMfaEnforced
}

// GetIsMfaEnforcedOk returns a tuple with the IsMfaEnforced field value
// and a boolean to check if the value has been set.
func (o *MfaPoliciesConfig) GetIsMfaEnforcedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMfaEnforced, true
}

// SetIsMfaEnforced sets field value
func (o *MfaPoliciesConfig) SetIsMfaEnforced(v bool) {
	o.IsMfaEnforced = v
}

func (o MfaPoliciesConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MfaPoliciesConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isMfaEnforced"] = o.IsMfaEnforced
	return toSerialize, nil
}

func (o *MfaPoliciesConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isMfaEnforced",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMfaPoliciesConfig := _MfaPoliciesConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMfaPoliciesConfig)

	if err != nil {
		return err
	}

	*o = MfaPoliciesConfig(varMfaPoliciesConfig)

	return err
}

type NullableMfaPoliciesConfig struct {
	value *MfaPoliciesConfig
	isSet bool
}

func (v NullableMfaPoliciesConfig) Get() *MfaPoliciesConfig {
	return v.value
}

func (v *NullableMfaPoliciesConfig) Set(val *MfaPoliciesConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableMfaPoliciesConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableMfaPoliciesConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMfaPoliciesConfig(val *MfaPoliciesConfig) *NullableMfaPoliciesConfig {
	return &NullableMfaPoliciesConfig{value: val, isSet: true}
}

func (v NullableMfaPoliciesConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMfaPoliciesConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
