/*
DRACOON API

REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>

API version: 5.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateOpenIdIdpConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOpenIdIdpConfigRequest{}

// UpdateOpenIdIdpConfigRequest Request model for updating an OpenID Connect IDP configuration
type UpdateOpenIdIdpConfigRequest struct {
	// Name of the IDP
	Name *string `json:"name,omitempty"`
	// Issuer identifier of the IDP  The value is a case sensitive URL.
	Issuer *string `json:"issuer,omitempty"`
	// URL of the authorization endpoint
	AuthorizationEndPointUrl *string `json:"authorizationEndPointUrl,omitempty"`
	// URL of the token endpoint
	TokenEndPointUrl *string `json:"tokenEndPointUrl,omitempty"`
	// URL of the user info endpoint
	UserInfoEndPointUrl *string `json:"userInfoEndPointUrl,omitempty"`
	// URL of the JWKS endpoint
	JwksEndPointUrl *string `json:"jwksEndPointUrl,omitempty"`
	// ID of the OpenID client
	ClientId *string `json:"clientId,omitempty"`
	// Secret, which client uses at authentication.
	ClientSecret *string `json:"clientSecret,omitempty"`
	// &#128640; Since v4.11.0  Flow, which is used at authentication
	Flow *string `json:"flow,omitempty"`
	// List of requested scopes  Usually `openid` and the names of the requested claims.
	Scopes []string `json:"scopes,omitempty"`
	// URIs, to which a user is redirected after authorization.
	RedirectUris []string `json:"redirectUris,omitempty"`
	// Determines whether PKCE is enabled.  cf. [RFC 7636](https://tools.ietf.org/html/rfc7636)
	PkceEnabled *bool `json:"pkceEnabled,omitempty"`
	// PKCE code challenge method.  cf. [RFC 7636](https://tools.ietf.org/html/rfc7636)
	PkceChallengeMethod *string `json:"pkceChallengeMethod,omitempty"`
	// Name of the claim which is used for the user mapping.
	MappingClaim *string `json:"mappingClaim,omitempty"`
	// Name of the claim which is used for the user mapping fallback.
	FallbackMappingClaim *string `json:"fallbackMappingClaim,omitempty"`
	// Set `true` to reset `fallbackMappingClaim`.
	ResetFallbackMappingClaim *bool `json:"resetFallbackMappingClaim,omitempty"`
	// &#128640; Since v4.23.0  Source, which is used to get user information at the import or update of a user.
	UserInfoSource *string `json:"userInfoSource,omitempty"`
	// Determines if a DRACOON account is automatically created for a new user  who successfully logs on with his / her AD / IDP account.
	UserImportEnabled *bool `json:"userImportEnabled,omitempty"`
	// User group that is assigned to users who are created by automatic import.  Reset with `0`
	UserImportGroup *int64 `json:"userImportGroup,omitempty"`
	// Determines if the DRACOON account is updated with data from AD / IDP.  For OpenID Connect, the scopes `email` and `profile` are needed.
	UserUpdateEnabled *bool `json:"userUpdateEnabled,omitempty"`
	// URL of the user management UI.  Use empty string to remove.
	UserManagementUrl *string `json:"userManagementUrl,omitempty"`
}

// NewUpdateOpenIdIdpConfigRequest instantiates a new UpdateOpenIdIdpConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOpenIdIdpConfigRequest() *UpdateOpenIdIdpConfigRequest {
	this := UpdateOpenIdIdpConfigRequest{}
	var pkceEnabled bool = false
	this.PkceEnabled = &pkceEnabled
	var userImportEnabled bool = false
	this.UserImportEnabled = &userImportEnabled
	var userUpdateEnabled bool = false
	this.UserUpdateEnabled = &userUpdateEnabled
	return &this
}

// NewUpdateOpenIdIdpConfigRequestWithDefaults instantiates a new UpdateOpenIdIdpConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOpenIdIdpConfigRequestWithDefaults() *UpdateOpenIdIdpConfigRequest {
	this := UpdateOpenIdIdpConfigRequest{}
	var pkceEnabled bool = false
	this.PkceEnabled = &pkceEnabled
	var userImportEnabled bool = false
	this.UserImportEnabled = &userImportEnabled
	var userUpdateEnabled bool = false
	this.UserUpdateEnabled = &userUpdateEnabled
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateOpenIdIdpConfigRequest) SetName(v string) {
	o.Name = &v
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *UpdateOpenIdIdpConfigRequest) SetIssuer(v string) {
	o.Issuer = &v
}

// GetAuthorizationEndPointUrl returns the AuthorizationEndPointUrl field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetAuthorizationEndPointUrl() string {
	if o == nil || IsNil(o.AuthorizationEndPointUrl) {
		var ret string
		return ret
	}
	return *o.AuthorizationEndPointUrl
}

// GetAuthorizationEndPointUrlOk returns a tuple with the AuthorizationEndPointUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetAuthorizationEndPointUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorizationEndPointUrl) {
		return nil, false
	}
	return o.AuthorizationEndPointUrl, true
}

// HasAuthorizationEndPointUrl returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasAuthorizationEndPointUrl() bool {
	if o != nil && !IsNil(o.AuthorizationEndPointUrl) {
		return true
	}

	return false
}

// SetAuthorizationEndPointUrl gets a reference to the given string and assigns it to the AuthorizationEndPointUrl field.
func (o *UpdateOpenIdIdpConfigRequest) SetAuthorizationEndPointUrl(v string) {
	o.AuthorizationEndPointUrl = &v
}

// GetTokenEndPointUrl returns the TokenEndPointUrl field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetTokenEndPointUrl() string {
	if o == nil || IsNil(o.TokenEndPointUrl) {
		var ret string
		return ret
	}
	return *o.TokenEndPointUrl
}

// GetTokenEndPointUrlOk returns a tuple with the TokenEndPointUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetTokenEndPointUrlOk() (*string, bool) {
	if o == nil || IsNil(o.TokenEndPointUrl) {
		return nil, false
	}
	return o.TokenEndPointUrl, true
}

// HasTokenEndPointUrl returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasTokenEndPointUrl() bool {
	if o != nil && !IsNil(o.TokenEndPointUrl) {
		return true
	}

	return false
}

// SetTokenEndPointUrl gets a reference to the given string and assigns it to the TokenEndPointUrl field.
func (o *UpdateOpenIdIdpConfigRequest) SetTokenEndPointUrl(v string) {
	o.TokenEndPointUrl = &v
}

// GetUserInfoEndPointUrl returns the UserInfoEndPointUrl field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetUserInfoEndPointUrl() string {
	if o == nil || IsNil(o.UserInfoEndPointUrl) {
		var ret string
		return ret
	}
	return *o.UserInfoEndPointUrl
}

// GetUserInfoEndPointUrlOk returns a tuple with the UserInfoEndPointUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetUserInfoEndPointUrlOk() (*string, bool) {
	if o == nil || IsNil(o.UserInfoEndPointUrl) {
		return nil, false
	}
	return o.UserInfoEndPointUrl, true
}

// HasUserInfoEndPointUrl returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasUserInfoEndPointUrl() bool {
	if o != nil && !IsNil(o.UserInfoEndPointUrl) {
		return true
	}

	return false
}

// SetUserInfoEndPointUrl gets a reference to the given string and assigns it to the UserInfoEndPointUrl field.
func (o *UpdateOpenIdIdpConfigRequest) SetUserInfoEndPointUrl(v string) {
	o.UserInfoEndPointUrl = &v
}

// GetJwksEndPointUrl returns the JwksEndPointUrl field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetJwksEndPointUrl() string {
	if o == nil || IsNil(o.JwksEndPointUrl) {
		var ret string
		return ret
	}
	return *o.JwksEndPointUrl
}

// GetJwksEndPointUrlOk returns a tuple with the JwksEndPointUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetJwksEndPointUrlOk() (*string, bool) {
	if o == nil || IsNil(o.JwksEndPointUrl) {
		return nil, false
	}
	return o.JwksEndPointUrl, true
}

// HasJwksEndPointUrl returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasJwksEndPointUrl() bool {
	if o != nil && !IsNil(o.JwksEndPointUrl) {
		return true
	}

	return false
}

// SetJwksEndPointUrl gets a reference to the given string and assigns it to the JwksEndPointUrl field.
func (o *UpdateOpenIdIdpConfigRequest) SetJwksEndPointUrl(v string) {
	o.JwksEndPointUrl = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *UpdateOpenIdIdpConfigRequest) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *UpdateOpenIdIdpConfigRequest) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetFlow returns the Flow field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetFlow() string {
	if o == nil || IsNil(o.Flow) {
		var ret string
		return ret
	}
	return *o.Flow
}

// GetFlowOk returns a tuple with the Flow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetFlowOk() (*string, bool) {
	if o == nil || IsNil(o.Flow) {
		return nil, false
	}
	return o.Flow, true
}

// HasFlow returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasFlow() bool {
	if o != nil && !IsNil(o.Flow) {
		return true
	}

	return false
}

// SetFlow gets a reference to the given string and assigns it to the Flow field.
func (o *UpdateOpenIdIdpConfigRequest) SetFlow(v string) {
	o.Flow = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *UpdateOpenIdIdpConfigRequest) SetScopes(v []string) {
	o.Scopes = v
}

// GetRedirectUris returns the RedirectUris field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetRedirectUris() []string {
	if o == nil || IsNil(o.RedirectUris) {
		var ret []string
		return ret
	}
	return o.RedirectUris
}

// GetRedirectUrisOk returns a tuple with the RedirectUris field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetRedirectUrisOk() ([]string, bool) {
	if o == nil || IsNil(o.RedirectUris) {
		return nil, false
	}
	return o.RedirectUris, true
}

// HasRedirectUris returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasRedirectUris() bool {
	if o != nil && !IsNil(o.RedirectUris) {
		return true
	}

	return false
}

// SetRedirectUris gets a reference to the given []string and assigns it to the RedirectUris field.
func (o *UpdateOpenIdIdpConfigRequest) SetRedirectUris(v []string) {
	o.RedirectUris = v
}

// GetPkceEnabled returns the PkceEnabled field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetPkceEnabled() bool {
	if o == nil || IsNil(o.PkceEnabled) {
		var ret bool
		return ret
	}
	return *o.PkceEnabled
}

// GetPkceEnabledOk returns a tuple with the PkceEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetPkceEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.PkceEnabled) {
		return nil, false
	}
	return o.PkceEnabled, true
}

// HasPkceEnabled returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasPkceEnabled() bool {
	if o != nil && !IsNil(o.PkceEnabled) {
		return true
	}

	return false
}

// SetPkceEnabled gets a reference to the given bool and assigns it to the PkceEnabled field.
func (o *UpdateOpenIdIdpConfigRequest) SetPkceEnabled(v bool) {
	o.PkceEnabled = &v
}

// GetPkceChallengeMethod returns the PkceChallengeMethod field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetPkceChallengeMethod() string {
	if o == nil || IsNil(o.PkceChallengeMethod) {
		var ret string
		return ret
	}
	return *o.PkceChallengeMethod
}

// GetPkceChallengeMethodOk returns a tuple with the PkceChallengeMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetPkceChallengeMethodOk() (*string, bool) {
	if o == nil || IsNil(o.PkceChallengeMethod) {
		return nil, false
	}
	return o.PkceChallengeMethod, true
}

// HasPkceChallengeMethod returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasPkceChallengeMethod() bool {
	if o != nil && !IsNil(o.PkceChallengeMethod) {
		return true
	}

	return false
}

// SetPkceChallengeMethod gets a reference to the given string and assigns it to the PkceChallengeMethod field.
func (o *UpdateOpenIdIdpConfigRequest) SetPkceChallengeMethod(v string) {
	o.PkceChallengeMethod = &v
}

// GetMappingClaim returns the MappingClaim field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetMappingClaim() string {
	if o == nil || IsNil(o.MappingClaim) {
		var ret string
		return ret
	}
	return *o.MappingClaim
}

// GetMappingClaimOk returns a tuple with the MappingClaim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetMappingClaimOk() (*string, bool) {
	if o == nil || IsNil(o.MappingClaim) {
		return nil, false
	}
	return o.MappingClaim, true
}

// HasMappingClaim returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasMappingClaim() bool {
	if o != nil && !IsNil(o.MappingClaim) {
		return true
	}

	return false
}

// SetMappingClaim gets a reference to the given string and assigns it to the MappingClaim field.
func (o *UpdateOpenIdIdpConfigRequest) SetMappingClaim(v string) {
	o.MappingClaim = &v
}

// GetFallbackMappingClaim returns the FallbackMappingClaim field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetFallbackMappingClaim() string {
	if o == nil || IsNil(o.FallbackMappingClaim) {
		var ret string
		return ret
	}
	return *o.FallbackMappingClaim
}

// GetFallbackMappingClaimOk returns a tuple with the FallbackMappingClaim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetFallbackMappingClaimOk() (*string, bool) {
	if o == nil || IsNil(o.FallbackMappingClaim) {
		return nil, false
	}
	return o.FallbackMappingClaim, true
}

// HasFallbackMappingClaim returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasFallbackMappingClaim() bool {
	if o != nil && !IsNil(o.FallbackMappingClaim) {
		return true
	}

	return false
}

// SetFallbackMappingClaim gets a reference to the given string and assigns it to the FallbackMappingClaim field.
func (o *UpdateOpenIdIdpConfigRequest) SetFallbackMappingClaim(v string) {
	o.FallbackMappingClaim = &v
}

// GetResetFallbackMappingClaim returns the ResetFallbackMappingClaim field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetResetFallbackMappingClaim() bool {
	if o == nil || IsNil(o.ResetFallbackMappingClaim) {
		var ret bool
		return ret
	}
	return *o.ResetFallbackMappingClaim
}

// GetResetFallbackMappingClaimOk returns a tuple with the ResetFallbackMappingClaim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetResetFallbackMappingClaimOk() (*bool, bool) {
	if o == nil || IsNil(o.ResetFallbackMappingClaim) {
		return nil, false
	}
	return o.ResetFallbackMappingClaim, true
}

// HasResetFallbackMappingClaim returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasResetFallbackMappingClaim() bool {
	if o != nil && !IsNil(o.ResetFallbackMappingClaim) {
		return true
	}

	return false
}

// SetResetFallbackMappingClaim gets a reference to the given bool and assigns it to the ResetFallbackMappingClaim field.
func (o *UpdateOpenIdIdpConfigRequest) SetResetFallbackMappingClaim(v bool) {
	o.ResetFallbackMappingClaim = &v
}

// GetUserInfoSource returns the UserInfoSource field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetUserInfoSource() string {
	if o == nil || IsNil(o.UserInfoSource) {
		var ret string
		return ret
	}
	return *o.UserInfoSource
}

// GetUserInfoSourceOk returns a tuple with the UserInfoSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetUserInfoSourceOk() (*string, bool) {
	if o == nil || IsNil(o.UserInfoSource) {
		return nil, false
	}
	return o.UserInfoSource, true
}

// HasUserInfoSource returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasUserInfoSource() bool {
	if o != nil && !IsNil(o.UserInfoSource) {
		return true
	}

	return false
}

// SetUserInfoSource gets a reference to the given string and assigns it to the UserInfoSource field.
func (o *UpdateOpenIdIdpConfigRequest) SetUserInfoSource(v string) {
	o.UserInfoSource = &v
}

// GetUserImportEnabled returns the UserImportEnabled field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetUserImportEnabled() bool {
	if o == nil || IsNil(o.UserImportEnabled) {
		var ret bool
		return ret
	}
	return *o.UserImportEnabled
}

// GetUserImportEnabledOk returns a tuple with the UserImportEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetUserImportEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.UserImportEnabled) {
		return nil, false
	}
	return o.UserImportEnabled, true
}

// HasUserImportEnabled returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasUserImportEnabled() bool {
	if o != nil && !IsNil(o.UserImportEnabled) {
		return true
	}

	return false
}

// SetUserImportEnabled gets a reference to the given bool and assigns it to the UserImportEnabled field.
func (o *UpdateOpenIdIdpConfigRequest) SetUserImportEnabled(v bool) {
	o.UserImportEnabled = &v
}

// GetUserImportGroup returns the UserImportGroup field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetUserImportGroup() int64 {
	if o == nil || IsNil(o.UserImportGroup) {
		var ret int64
		return ret
	}
	return *o.UserImportGroup
}

// GetUserImportGroupOk returns a tuple with the UserImportGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetUserImportGroupOk() (*int64, bool) {
	if o == nil || IsNil(o.UserImportGroup) {
		return nil, false
	}
	return o.UserImportGroup, true
}

// HasUserImportGroup returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasUserImportGroup() bool {
	if o != nil && !IsNil(o.UserImportGroup) {
		return true
	}

	return false
}

// SetUserImportGroup gets a reference to the given int64 and assigns it to the UserImportGroup field.
func (o *UpdateOpenIdIdpConfigRequest) SetUserImportGroup(v int64) {
	o.UserImportGroup = &v
}

// GetUserUpdateEnabled returns the UserUpdateEnabled field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetUserUpdateEnabled() bool {
	if o == nil || IsNil(o.UserUpdateEnabled) {
		var ret bool
		return ret
	}
	return *o.UserUpdateEnabled
}

// GetUserUpdateEnabledOk returns a tuple with the UserUpdateEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetUserUpdateEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.UserUpdateEnabled) {
		return nil, false
	}
	return o.UserUpdateEnabled, true
}

// HasUserUpdateEnabled returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasUserUpdateEnabled() bool {
	if o != nil && !IsNil(o.UserUpdateEnabled) {
		return true
	}

	return false
}

// SetUserUpdateEnabled gets a reference to the given bool and assigns it to the UserUpdateEnabled field.
func (o *UpdateOpenIdIdpConfigRequest) SetUserUpdateEnabled(v bool) {
	o.UserUpdateEnabled = &v
}

// GetUserManagementUrl returns the UserManagementUrl field value if set, zero value otherwise.
func (o *UpdateOpenIdIdpConfigRequest) GetUserManagementUrl() string {
	if o == nil || IsNil(o.UserManagementUrl) {
		var ret string
		return ret
	}
	return *o.UserManagementUrl
}

// GetUserManagementUrlOk returns a tuple with the UserManagementUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOpenIdIdpConfigRequest) GetUserManagementUrlOk() (*string, bool) {
	if o == nil || IsNil(o.UserManagementUrl) {
		return nil, false
	}
	return o.UserManagementUrl, true
}

// HasUserManagementUrl returns a boolean if a field has been set.
func (o *UpdateOpenIdIdpConfigRequest) HasUserManagementUrl() bool {
	if o != nil && !IsNil(o.UserManagementUrl) {
		return true
	}

	return false
}

// SetUserManagementUrl gets a reference to the given string and assigns it to the UserManagementUrl field.
func (o *UpdateOpenIdIdpConfigRequest) SetUserManagementUrl(v string) {
	o.UserManagementUrl = &v
}

func (o UpdateOpenIdIdpConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOpenIdIdpConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Issuer) {
		toSerialize["issuer"] = o.Issuer
	}
	if !IsNil(o.AuthorizationEndPointUrl) {
		toSerialize["authorizationEndPointUrl"] = o.AuthorizationEndPointUrl
	}
	if !IsNil(o.TokenEndPointUrl) {
		toSerialize["tokenEndPointUrl"] = o.TokenEndPointUrl
	}
	if !IsNil(o.UserInfoEndPointUrl) {
		toSerialize["userInfoEndPointUrl"] = o.UserInfoEndPointUrl
	}
	if !IsNil(o.JwksEndPointUrl) {
		toSerialize["jwksEndPointUrl"] = o.JwksEndPointUrl
	}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	if !IsNil(o.Flow) {
		toSerialize["flow"] = o.Flow
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.RedirectUris) {
		toSerialize["redirectUris"] = o.RedirectUris
	}
	if !IsNil(o.PkceEnabled) {
		toSerialize["pkceEnabled"] = o.PkceEnabled
	}
	if !IsNil(o.PkceChallengeMethod) {
		toSerialize["pkceChallengeMethod"] = o.PkceChallengeMethod
	}
	if !IsNil(o.MappingClaim) {
		toSerialize["mappingClaim"] = o.MappingClaim
	}
	if !IsNil(o.FallbackMappingClaim) {
		toSerialize["fallbackMappingClaim"] = o.FallbackMappingClaim
	}
	if !IsNil(o.ResetFallbackMappingClaim) {
		toSerialize["resetFallbackMappingClaim"] = o.ResetFallbackMappingClaim
	}
	if !IsNil(o.UserInfoSource) {
		toSerialize["userInfoSource"] = o.UserInfoSource
	}
	if !IsNil(o.UserImportEnabled) {
		toSerialize["userImportEnabled"] = o.UserImportEnabled
	}
	if !IsNil(o.UserImportGroup) {
		toSerialize["userImportGroup"] = o.UserImportGroup
	}
	if !IsNil(o.UserUpdateEnabled) {
		toSerialize["userUpdateEnabled"] = o.UserUpdateEnabled
	}
	if !IsNil(o.UserManagementUrl) {
		toSerialize["userManagementUrl"] = o.UserManagementUrl
	}
	return toSerialize, nil
}

type NullableUpdateOpenIdIdpConfigRequest struct {
	value *UpdateOpenIdIdpConfigRequest
	isSet bool
}

func (v NullableUpdateOpenIdIdpConfigRequest) Get() *UpdateOpenIdIdpConfigRequest {
	return v.value
}

func (v *NullableUpdateOpenIdIdpConfigRequest) Set(val *UpdateOpenIdIdpConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOpenIdIdpConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOpenIdIdpConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOpenIdIdpConfigRequest(val *UpdateOpenIdIdpConfigRequest) *NullableUpdateOpenIdIdpConfigRequest {
	return &NullableUpdateOpenIdIdpConfigRequest{value: val, isSet: true}
}

func (v NullableUpdateOpenIdIdpConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOpenIdIdpConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
